Vagrant.configure(2) do | config |
  config.ssh.insert_key = false
  config.ssh.username = 'vagrant'
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Debian 8
  config.vm.define "debian8" do |wekan|
    wekan.vm.hostname = "debian8.dev"
    wekan.vm.box = "debian/jessie64"
    wekan.vm.network :private_network, ip: "192.168.60.3"
    wekan.vm.network "forwarded_port", guest: 3000, host: 4000
    wekan.vm.network "forwarded_port", guest: 443, host: 4430
  end


  # Ubuntu 15.04
  config.vm.define "ubuntu15" do |wekan|
    wekan.vm.hostname = "ubuntu15.dev"
    wekan.vm.box = "ubuntu/vivid64"
    wekan.vm.network :private_network, ip: "192.168.60.4"
    wekan.vm.network "forwarded_port", guest: 3000, host: 4001
    wekan.vm.network "forwarded_port", guest: 443, host: 4431
  end

  # Ubuntu 14.04
  config.vm.define "ubuntu14" do |wekan|
    wekan.vm.hostname = "ubuntu14.dev"
    wekan.vm.box = "ubuntu/trusty64"
    wekan.vm.network :private_network, ip: "192.168.60.5"
    wekan.vm.network "forwarded_port", guest: 3000, host: 4002
    wekan.vm.network "forwarded_port", guest: 443, host: 4432
  end

  # CentOS 7
  config.vm.define "centos7" do |wekan|
    wekan.vm.hostname = "centos7.dev"
    wekan.vm.box = "geerlingguy/centos7"
    wekan.vm.network :private_network, ip: "192.168.60.6"
    wekan.vm.network "forwarded_port", guest: 3000, host: 4003
    wekan.vm.network "forwarded_port", guest: 443, host: 4433
  end

  # Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "wekan_servers" => ["debian8", "ubuntu14", "ubuntu15", "centos7"],
      "all_groups:children" => ["wekan_servers"]
    }

    ansible.extra_vars = {
      wekan_service_host: "localhost",
      wekan_automatic_upgrades: 'true',
    }

    ansible.sudo = true
    ansible.playbook = "provision.yml"
  end
end
